2021-10-11 12:01:13,925 (13193/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "/usr/bin/less"
2021-10-11 12:01:13,926 (13193/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2021-10-11 12:01:13,931 (13193/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/Users/luca/.local/pipx/venvs/pgcli/lib/python3.10/site-packages/pgcli/main.py", line 594, in connect\n    raise e\n  File "/Users/luca/.local/pipx/venvs/pgcli/lib/python3.10/site-packages/pgcli/main.py", line 581, in connect\n    pgexecute = PGExecute(database, user, passwd, host, port, dsn, **kwargs)\n  File "/Users/luca/.local/pipx/venvs/pgcli/lib/python3.10/site-packages/pgcli/pgexecute.py", line 260, in __init__\n    self.connect(database, user, password, host, port, dsn, **kwargs)\n  File "/Users/luca/.local/pipx/venvs/pgcli/lib/python3.10/site-packages/pgcli/pgexecute.py", line 306, in connect\n    conn = psycopg2.connect(**conn_params)\n  File "/Users/luca/.local/pipx/venvs/pgcli/lib/python3.10/site-packages/psycopg2/__init__.py", line 122, in connect\n    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)\npsycopg2.OperationalError: connection to server on socket "/tmp/.s.PGSQL.5432" failed: No such file or directory\n\tIs the server running locally and accepting connections on that socket?\n\n'
2021-10-11 12:01:19,792 (13261/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "/usr/bin/less"
2021-10-11 12:01:19,793 (13261/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2021-10-11 12:01:19,798 (13261/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/Users/luca/.local/pipx/venvs/pgcli/lib/python3.10/site-packages/pgcli/main.py", line 594, in connect\n    raise e\n  File "/Users/luca/.local/pipx/venvs/pgcli/lib/python3.10/site-packages/pgcli/main.py", line 581, in connect\n    pgexecute = PGExecute(database, user, passwd, host, port, dsn, **kwargs)\n  File "/Users/luca/.local/pipx/venvs/pgcli/lib/python3.10/site-packages/pgcli/pgexecute.py", line 260, in __init__\n    self.connect(database, user, password, host, port, dsn, **kwargs)\n  File "/Users/luca/.local/pipx/venvs/pgcli/lib/python3.10/site-packages/pgcli/pgexecute.py", line 306, in connect\n    conn = psycopg2.connect(**conn_params)\n  File "/Users/luca/.local/pipx/venvs/pgcli/lib/python3.10/site-packages/psycopg2/__init__.py", line 122, in connect\n    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)\npsycopg2.OperationalError: connection to server on socket "/tmp/.s.PGSQL.5432" failed: No such file or directory\n\tIs the server running locally and accepting connections on that socket?\n\n'
2021-10-11 12:01:38,127 (13397/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "/usr/bin/less"
2021-10-11 12:01:38,128 (13397/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2021-10-11 12:03:26,610 (13397/MainThread) pgcli.pgexecute ERROR - sql: 'FROM bikemi_rentals SELECT COUNT(bikemi_rentals.bici), bikemi_rentals.nome_stazione_prelievo GROUP BY bikemi_rentals.nome_stazione_prelievo', error: SyntaxError('syntax error at or near "FROM"\nLINE 1: FROM bikemi_rentals SELECT COUNT(bikemi_rentals.bici), bikem...\n        ^\n')
2021-10-11 12:03:26,610 (13397/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/Users/luca/.local/pipx/venvs/pgcli/lib/python3.10/site-packages/pgcli/pgexecute.py", line 472, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/Users/luca/.local/pipx/venvs/pgcli/lib/python3.10/site-packages/pgcli/pgexecute.py", line 507, in execute_normal_sql\n    cur.execute(split_sql)\n  File "/Users/luca/.local/pipx/venvs/pgcli/lib/python3.10/site-packages/pgcli/pgexecute.py", line 168, in execute\n    psycopg2.extensions.cursor.execute(self, sql, args)\npsycopg2.errors.SyntaxError: syntax error at or near "FROM"\nLINE 1: FROM bikemi_rentals SELECT COUNT(bikemi_rentals.bici), bikem...\n        ^\n\n'
